title: Prateek Kumar
email: prateek@prateekkumar.in
description: >-
  Undergraduate student at Department of
  Computer Science and Engineering, Indian Institute of Technology Hyderabad.
baseurl: ""
url: "https://prateekkumar.in"
author: "Prateek Kumar"

timezone: Asia/Kolkata

# Build settings
markdown: kramdown
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-minifier
  - liquid-md5
  - jekyll-email-protect
  - jemoji
  - jekyll-sitemap
  - jekyll-gist

include:
  - _redirects

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE
  - README.md
